[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
sqlx = { version = "0", features = ["runtime-tokio", "postgres", "uuid"] }
uuid = "1"
serde = "1"
serde_json = "1"
chrono = "0"
jsonwebtoken = "9"